export default {
  name: "Parvin Zangeneh",
  home: "HOME",
  resume: "RESUME",
  portfolios: "PORTFOLIOS",
  about: "ABOUT ME",
  contact: "CONTACT",
  hi: "Hi,I am ",
  hi2: "",
  aboutMeTitle: "ABOUT ME",
  fullName: "Full Name",
  cityTitle: "City",
  language: "Language",
  AgeTitle: "Age",
  age: "1995",
  city: "Kermanshah",
  services: "Services",
  webdeveloper: 'Web Developer',
  webdesigne: 'Web Design',
  resumeTitle: 'MY SKILLS',
  workingExperiance: "Work Experiences",
  education: "Education",
  description: "I started my activity in Front End in 2017. I'm trying to continue the React framework.",

  softwareEngineer: "Bachelor's of Science - Software Engineer",
  working: "Web-Developer, Front-End ",
  FieldOfWork: "Field of work",
  year: "2017",
  FullIntroduce:"I am Parvin Zanganeh. I have a bachelor's degree in software engineering. I am very interested in programming and learning different frameworks. I also had a background in back-end, but I enjoy designing and working in front-end. Finding the challenges of each framework has its own charm, and I enjoy being able to show coding with its charms. I am also interested in the fields of artificial intelligence, data analysis, and databases. And these new topics definitely have a significant impact on making web pages more secure, which leads to the discussion of cybersecurity, which is one of the most central topics in the field of web development and programming",
  educationSteps: [
    { id: 0, date: "2005-2008", title: "Elementary-school", subtitle: "karaj univercity", content: "I spent my elementary school in Ehsan school in Kermanshah province" },
    { id: 1, date: "2009-2011", title: "Middle-school", subtitle: "kermanshah univercity", content: "I spent my middle school years at an Iraqi school on Saadi Street" },
    { id: 3, date: "2012-2013", title: "High-school", subtitle: "kermanshah univercity", content: "I spent my high school years at Jafari High School on Red Crescent Street (Shirokhorshid)" },
    { id: 4, date: "2014-2017", title: "University", subtitle: "kermanshah univercity", content: "I completed my bachelor's degree in software engineering at Karaj University" },
  ],

  workingExperianceSteps: [
    { id: 0,
       date: "2017-2019",
        title: "APA Razi university",
         content: 
         "Software Expert & Researcher - APA-CSIRT (computer security incident response team) company, Kermanshah •	Design, Collecting and preparing a database of hardware and software information for Kermanshah Province's regional electricity in Excel •	Translate articles and up-to-date news on cyber attacks and web applications into Persian for publication in the company's internal news bulletin •	Designing a system for issuing Razi University personnel cards - two-person team, with Laravel Framework and PHP programming language  •	Designing a system for Razi University graduates - two-person team, with Laravel Framework and PHP programming language",
         },

    { id: 1,
       date: "2019-2020",
        title: "APA Razi university",
         content: 
         "APA-CSIRT(computer security incident response team) company, Kermanshah-•	Designed and implemented Website and competition platform for first round of Razi University's Capture The Flag (CTF- Capture The Flag) competitions, Three-person teamwork - with Laravel Framework and PHP programming language, Implementation of database and competition website for several fields such as web hacking-networking-programming and etc.•	Full-time position with social security insurance coverage",
         },
    { id: 2,
          date: "2019-2020",
           title: "Rad Pardaz Razi",
            content: "Native Cyber Exhibition, APA Specialized Center of Razi University, Location for international exhibition, Tehran , Presenting, Providing solutions, training workshops and native products in the field of electrical and computer.  Contact:   083-34343251, APA center - ELECOMP- Electrical and Computer Exhibition, APA Specialized Center of Razi University, location of international exhibitions, Kermanshah -The presence of more than 60 companies in the fields of electronics, computer, and trade to present computer products, Security, and information security in cyberspace.",
            },
    { id: 3,
              date: "2019-2020",
               title: "Rad Pardaz Razi",
                content: "Radpardaz Razi company, Kermanshah, Iran •	Designed and implemented Website and competition platform for second round of Razi University's Capture The Flag (CTF- Capture The Flag) competitions, Two-person teamwork - with React Framework and JavaScript programming language. •	Full-time position with social security insurance coverage",
                },
                { id: 3,
                  date: "2019-2020",
                   title: "Rad Pardaz Razi",
                   content:"•	Designed and developed a website for third round of Razi University's Capture The Flag (CTF) international competitions, Entire Front-End section (just myself), Effectively implemented system (frontend) in React.js framework, JavaScript programming language, Bilingual implementation (English, Persian), Fully responsive implementation for any device•	Full-time position with social security insurance coverage",
                }
  ],

  contactMe: "CONTACT ME",

  phone: "Phone",
  email: "Email",
  address: "Address",

  portfolioList: [
    { id: 0, title: "ctf razi", des: "CTF(capture the flag)", image: "http://localhost:3000/static/media/hossin.d3dc2e7b.jpg", link: "https://ctf.razi.ac.ir" },
    { id: 1, title: "cylab", des: "cylab(Hacking skill test)", image: "http://localhost:3000/static/media/hossin.d3dc2e7b.jpg", link: "http://cylab.ir" },
  ],
  noData: "No Data",
  Ability: "Languages",
  abilityDes: "PHP, C/C++, HTML, C#, CSS, JavaScript",
  documentsDes1: "•	CEH (Certified Ethical Hacker) from APA Company, Razi University, Kermanshah, Iran , Mar 2018 – Jul 2018 ,",
  documentsDes2: "•	SOC (Security Operations Center) from BATIS ACADEMY and APA Company, Kermanshah, Nov 2018", 
  documents: "Certificate",
  WebTools:"Database Systems, Tools & Frameworks",
  webToolDes:"MySQL, Laravel PHP Framework, React.js Framework, ASP.net Framework, GitHub, Git",
  skillLangTitle:"Language skills",
  skillLangDes:"Mother tongue-Persian   English-TOEFL",
}